apiVersion: apps/v1
kind: Deployment
metadata:
  name: podplacementdeployment
  labels:
    app: reliablity
spec:
  replicas: 10
  selector:
    matchLabels:
      app: reliability
  template:
    metadata:
      labels:
        app: reliability
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            foo: reliability
      containers:
      - name: pause
        image: k8s.gcr.io/pause:3.1
      