apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzurePodSpreadConstraintsEnforced
metadata:
  name: prp-pod-spreadconstraint-mandate
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    excludedContainers: {{ .Values.excludedContainers }}
    excludedImages: {{ .Values.excludedImages }}